# Generated by Django 4.0.4 on 2022-06-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=30)),
                ('popularity', models.FloatField()),
                ('category', models.CharField(max_length=30)),
                ('tags', models.ManyToManyField(to='quotesApp.tag')),
            ],
        ),
    ]
