# Generated by Django 4.0.4 on 2022-06-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='author',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='category',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='tags',
        ),
        migrations.AddField(
            model_name='quote',
            name='character',
            field=models.CharField(default='-', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='topic',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
